/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c86630c6-6b6d-404f-b456-46e046e2989a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VWkGVRc2D",
    "aws_user_pools_web_client_id": "tv9abdmgi1800pn6jrd2cruqf",
    "oauth": {}
};

export default awsmobile;
