/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:551b4141-5693-4361-9a3b-0cd538a03658",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Gwa8UTw7F",
    "aws_user_pools_web_client_id": "7cba20fn2asrg20mij3cl3iohc",
    "oauth": {}
};

export default awsmobile;
