/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5183649b-1975-4ef4-abfd-503fa69d1bfb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SE0yKXBMd",
    "aws_user_pools_web_client_id": "45r0da8amlg24317iorji9q058",
    "oauth": {}
};

export default awsmobile;
